version: '3.9'
services:
    api:
        build: .
        env_file:
            - .env
            - ../.env
        environment:
            - DATABASE_URL=mysql://root:${DB_PASS}@host.docker.internal:${DB_PORT}/${DB_NAME}
        depends_on:
            - db
        ports:
            - ${APP_PORT:-80}:3000
        volumes:
            - ./src:/app/src
            - ./prisma:/app/prisma
    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASS:?No password set}
            - MYSQL_DATABASE=${DB_NAME:-musicdb}
            - MYSQL_USER=${DB_USER:-musicphpapp}
            - MYSQL_PASSWORD=${DB_PASS:?No password set}
        ports:
            - ${DB_PORT:-3306}:3306
